In [1]:
import numpy as np

In [2]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv
array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])
yv
array([[0.,  0.,  0.],
       [1.,  1.,  1.]])


NameError: name 'array' is not defined

In [3]:
nx, ny = (3, 2)

In [4]:
nx

3

In [5]:
ny

2

In [6]:
nx, ny

(3, 2)

In [7]:
a, b = 23, 34

In [8]:
a

23

In [9]:
b

34

In [12]:
type(a)

int

In [18]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
print(x)
y = np.linspace(0, 1, ny)
xv = np.meshgrid(x)
print(xv)
print(xv.shape)


[0.  0.5 1. ]
[array([0. , 0.5, 1. ])]


AttributeError: 'list' object has no attribute 'shape'

In [21]:
th_0 = np.linspace(start = -1, stop = 3, num = 5)
th_0

array([-1.,  0.,  1.,  2.,  3.])

In [24]:
a, b = np.meshgrid(th_0, th_0)
print(a)
print(b)

[[-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]
 [-1.  0.  1.  2.  3.]]
[[-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]]
