# Imports

In [23]:
from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(404)

In [24]:
import os
import numpy as np

# Constants

In [59]:
X_TRAIN_PATH = 'Data/digit_xtrain.csv'
X_TEST_PATH = 'Data/digit_xtest.csv'
Y_TRAIN_PATH = 'Data/digit_ytrain.csv'
Y_TEST_PATH = 'Data/digit_ytest.csv'

NR_CLASSES = 10

# Get the Data

In [26]:
%%time

y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter = ',', dtype = int)

CPU times: total: 297 ms
Wall time: 303 ms


In [27]:
y_train_all.shape

(60000,)

In [28]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter= ',', dtype = int)
y_test.shape

(10000,)

In [29]:
%%time

x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter = ',', dtype = int)

CPU times: total: 40.4 s
Wall time: 40.5 s


In [30]:
%%time

x_test = np.loadtxt(X_TEST_PATH, delimiter = ',', dtype = int)

CPU times: total: 6.62 s
Wall time: 6.67 s


In [31]:
print(x_train_all.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


# Explore the Data

In [32]:
x_train_all.shape

(60000, 784)

In [36]:
x_train_all[0].shape

(784,)

In [38]:
# 0 means complete white and 255 means complete black
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [40]:
y_train_all.shape

(60000,)

In [43]:
#y_train_all[0] 
y_train_all[:5]  # shows the output classes

array([5, 0, 4, 1, 9])

# Data Preprocessing

In [47]:
# Re-scale the features
x_train_all, x_test = x_train_all/255.0, x_test/255.0

In [57]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.eye(10)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

### Convert target value to one-hot encoding 

In [60]:
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [64]:
y_train_all[:9] 

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
y_train_all.shape

(60000, 10)

In [66]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)